### Obteniendo usuarios
GET http://localhost:3000/api/usrs

### Obteniendo usuario
GET http://localhost:3000/api/usrs/Alan

### Creando usuario
POST http://localhost:3000/api/usrs
Content-Type: application/json

{
    message: "hola"
}