import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { ThemeProvider } from "@mui/material/styles";
import darkTheme from "../theme.jsx";

import CssBaseline from "@mui/material/CssBaseline";

import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next-Time",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={darkTheme}>
            <CssBaseline />
            <Providers><div style={{ background: "#93A2B9" }}>{children}</div></Providers>
            
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
